name: Push on branches check
on:
  push:
    branches:
      - develop
    paths-ignore:
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4